### ISSUE TITLE
Can't assign requested address

### ISSUE THREAD

**Issue by kodeine** [arantonitis/pynat#4]
pynat --source_ip `<public IP>`
I get the following error,
```
sock.bind((source_ip, source_port))
OSError: [Errno 49] Can't assign requested address
```
If i try with 0.0.0.0 which is the default then it works fine. I want to test this against another public ip.

**Comment by aarant** [comment]
The socket will only bind to the IP addresses of your network interfaces. `0.0.0.0` just binds to all IPv4 addresses available to all interfaces: https://stackoverflow.com/a/3655796

If you are behind a NAT of any kind, you can only bind to any of the internal addresses, you won't be able to bind to the public IP of your machine, because your machine only knows the IP addresses assigned to it by your router.

If you're not behind a NAT, the IP address of your network interface is probably also your public IP, so you could bind to it. The failure isn't a bug, it's that the IP address you provided isn't the IP address of any of your network interfaces on your local network.

Also, I edited your post to not expose an actual IP address.
